# Generated by Django 2.1.7 on 2019-05-08 05:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(0, '事前準備'), (1, '重心試験'), (2, '回転試験'), (3, '機体搬出'), (4, '組み立て'), (5, '転がし試験'), (6, '滑走試験'), (7, 'ジャンプ試験'), (8, '飛行試験'), (9, '解体撤収'), (10, 'その他')], default=10, max_length=20, verbose_name='類名')),
                ('advantage', models.CharField(blank=True, max_length=2000, verbose_name='良かった点')),
                ('disadvantage', models.CharField(blank=True, max_length=2000, verbose_name='反省点')),
                ('improvement', models.CharField(blank=True, max_length=2000, verbose_name='改善案')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('tf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.TestFlightType', verbose_name='TFタイプ')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.Summary', verbose_name='総括'),
        ),
    ]
